name = "project-workbench-backup-worker"
main = "backup-worker.js"
compatibility_date = "2025-09-29"

# 触发器配置 - 每天凌晨 2 点运行
[triggers]
crons = ["0 2 * * *"]

# 绑定 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "project-workbench-db"
database_id = "1ad2c7c1-6515-4bf8-98fa-6b25f2338c46"

# 绑定 R2 存储桶
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "data-backups"

# 环境变量
[vars]
D1_DATABASE_NAME = "project-workbench-db"
R2_BUCKET_NAME = "data-backups"
BACKUP_PREFIX = "project-workbench-backup"
RETENTION_DAYS = "10"
MAX_BACKUPS = "10"